name: _Prepare

on:
  push:
    branches: main

jobs:
  test:
    name: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Save PR number
        run: |
          ###################################
          # Prerequisites

          # Update the list of packages
          sudo apt-get update

          # Install pre-requisite packages.
          sudo apt-get install -y wget apt-transport-https software-properties-common

          # Get the version of Ubuntu
          source /etc/os-release

          # Download the Microsoft repository keys
          wget -q https://packages.microsoft.com/config/ubuntu/$VERSION_ID/packages-microsoft-prod.deb

          # Register the Microsoft repository keys
          sudo dpkg -i packages-microsoft-prod.deb

          # Delete the the Microsoft repository keys file
          rm packages-microsoft-prod.deb

          # Update the list of packages after we added packages.microsoft.com
          sudo apt-get update

          ###################################
          # Install PowerShell
          sudo apt-get install -y powershell

          # Start PowerShell
          pwsh -v